/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.DanhMuc_model;
import Model.HoaDon_model;
import Model.KhachHang_model;
import Model.Loai_model;
import Model.MauSac_model;
import Model.NhanVien_model;
import Model.SanPham_model;
import Model.Size_model;
import Service.DanhMuc_Service;
import Service.HoaDon_service;
import Service.KhachHang_service;
import Service.Loai_Service;
import Service.MauSac_Service;
import Service.NhanVien_service;
import Service.SanPham_Service;
import Service.Size_Service;
import Service_impl.DanhMuc_impl;
import Service_impl.HoaDon_impl;
import Service_impl.Loai_impl;
import Service_impl.MauSac_impl;
import Service_impl.NhanVien_impl;
import Service_impl.SanPham_impl;
import Service_impl.Size_impl;
import Service_impl.khachHang_impl;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import GUI.Home_GUI;
import Model.HoaDonChiTiet_model;
import Service.HoaDonCT_service;
import Service_impl.HoaDonCT_imple;
import javax.swing.JFrame;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;

//java mail
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author tuan0
 */
public class BanHang_GUI extends javax.swing.JPanel {
//SanPham

    List<DanhMuc_model> listDanhMuc = new ArrayList<>();
    List<Loai_model> listLoai = new ArrayList<>();
    List<MauSac_model> listMau = new ArrayList<>();
    List<Size_model> listSize = new ArrayList<>();
    List<SanPham_model> listSanPham;
    DanhMuc_impl danhMucService = new DanhMuc_Service();
    Loai_impl loaiService = new Loai_Service();
    MauSac_impl mauService = new MauSac_Service();
    Size_impl sizeService = new Size_Service();
    SanPham_impl sanPhamService = new SanPham_Service();
//    hoaDon
    List<HoaDon_model> listHoaDon = new ArrayList<>();
    HoaDon_impl hoaDon_service = new HoaDon_service();
    DefaultTableModel model = new DefaultTableModel();
//    HoaDonCT
    List<HoaDonChiTiet_model> listHoaDonCT = new ArrayList<>();
    HoaDonCT_imple hoaDonCT_service = new HoaDonCT_service();
//    NhanVien_khachHang
    NhanVien_impl nhanVien_service = new NhanVien_service();
    khachHang_impl khachHang_service = new KhachHang_service();

    int index;

    /**
     * Creates new form BanHang_GUI
     */
    public BanHang_GUI() {
        initComponents();
        ShowTableSanPham();
        ShowTableHoaDon();
        txtTienHang.setEnabled(false);
        txtPhaiTra.setEnabled(false);
        txtChietKhau.setEnabled(false);
        txtTienTichLuy.setEnabled(false);
        txtTienTichLuy.setEnabled(false);
        txtSDT.setEnabled(false);
        txtTen.setEnabled(false);
        txtTienThuong.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtSDT = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtTienTichLuy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioiHang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtTienHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtChietKhau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTienThuong = new javax.swing.JTextField();
        txtPhaiTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnTaoHoaDon = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        txtMaHD = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cboDanhMucSearch = new javax.swing.JComboBox<>();
        cboLoaiSearch = new javax.swing.JComboBox<>();
        cboMauSearch = new javax.swing.JComboBox<>();
        cboSizeSearch = new javax.swing.JComboBox<>();
        txtTenSanPhamSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setBackground(new java.awt.Color(70, 130, 180));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("SDT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tích lũy");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienTichLuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblGioiHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        tblGioiHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioiHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioiHang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tiền hàng");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tiền thưởng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Chiết khấu");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tiền phải trả");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThuong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhaiTra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPhaiTra, txtTienThuong});

        btnTaoHoaDon.setBackground(new java.awt.Color(70, 130, 180));
        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHoaDon.setText("Tạo hóa đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(70, 130, 180));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Thanh toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(70, 130, 180));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hủy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Khách", "Nhân viên", "Ngày tạo", "Tổng tiền", "Trạng thái"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaHD)
                .addGap(74, 74, 74))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtMaHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên sản phẩm", "Size", "Màu", "Số lượng", "Giá tiền", "Title 7"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSP);
        if (tblSP.getColumnModel().getColumnCount() > 0) {
            tblSP.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cboDanhMucSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDanhMucSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhMucSearchActionPerformed(evt);
            }
        });

        cboLoaiSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSearchActionPerformed(evt);
            }
        });

        cboMauSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMauSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMauSearchActionPerformed(evt);
            }
        });

        cboSizeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSizeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSizeSearchActionPerformed(evt);
            }
        });

        txtTenSanPhamSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamSearchActionPerformed(evt);
            }
        });
        txtTenSanPhamSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenSanPhamSearchKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tên sản phẩm");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Danh mục");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Loại");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Màu");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Size");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("LỌC");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDanhMucSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel12)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel13))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cboLoaiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMauSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSizeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(txtTenSanPhamSearch))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDanhMucSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMauSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSizeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSanPhamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(26, 26, 26))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboDanhMucSearch, cboLoaiSearch, cboMauSearch, cboSizeSearch, txtTenSanPhamSearch});

        jButton2.setText("Mail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(270, 270, 270))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiSearchActionPerformed

    private void cboMauSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMauSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMauSearchActionPerformed

    private void cboSizeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSizeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSizeSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frameChild = new JFrame();
        frameChild.setSize(1200, 900);
        frameChild.setLocationRelativeTo(null);
        frameChild.add(new KhachHang_GUI());
        frameChild.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:
        index = tblSP.getSelectedRow();
        ThemHoaDonCT(index);
        TienHang();
    }//GEN-LAST:event_tblSPMouseClicked

    private void tblGioiHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioiHangMouseClicked
        // TODO add your handling code here:
        index = tblGioiHang.getSelectedRow();
        DeleteSanPhamHDCT();
    }//GEN-LAST:event_tblGioiHangMouseClicked

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        TaoHoaDon();
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        index = tblHoaDon.getSelectedRow();
        ShowFormHoaDon(hoaDon_service.selectHoaDon().get(index));
        txtTienHang.setText(TienHang() + "");
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tblGioiHang.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm để thanh toán");
        } else {
            int tt = 1;
            updateTrangThaiHD(tt);
            inHoaDon();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int tt = 2;
        updateTrangThaiHD(2);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtTenSanPhamSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanPhamSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTenSanPhamSearchActionPerformed

    private void txtTenSanPhamSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSanPhamSearchKeyReleased
        // TODO add your handling code here:
        ShowTableSanPhamByTen(txtTenSanPhamSearch.getText());
    }//GEN-LAST:event_txtTenSanPhamSearchKeyReleased

    private void cboDanhMucSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhMucSearchActionPerformed
//        // TODO add your handling code here:
//        String tendm = cboDanhMucSearch.getSelectedItem()+"";
//        ShowTableSanPhamByChiTiet(tendm);
//        System.out.println(tendm);
    }//GEN-LAST:event_cboDanhMucSearchActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JComboBox<String> cboDanhMucSearch;
    private javax.swing.JComboBox<String> cboLoaiSearch;
    private javax.swing.JComboBox<String> cboMauSearch;
    private javax.swing.JComboBox<String> cboSizeSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGioiHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSP;
    public static javax.swing.JTextField txtChietKhau;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JTextField txtPhaiTra;
    public static javax.swing.JTextField txtSDT;
    public static javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenSanPhamSearch;
    private javax.swing.JTextField txtTienHang;
    private javax.swing.JTextField txtTienThuong;
    public static javax.swing.JTextField txtTienTichLuy;
    // End of variables declaration//GEN-END:variables

    private void TaoHoaDon() {
        int count = Integer.parseInt(hoaDon_service.selectHoaDon().get(0).getMaHD().substring(2, hoaDon_service.selectHoaDon().get(0).getMaHD().length())) + 1;
        String ma = "HD" + count;
        KhachHang_model kh;
        Home_GUI home = new Home_GUI();
        
        kh = khachHang_service.selectByID(txtSDT.getText());
        System.out.println(txtSDT.getText());
//        Home_GUI b = new Home_GUI();
//        LocalDate ngay = LocalDate.now();
//        NhanVien_model nv = nhanVien_service.selectByID("12");
//        System.out.println(ngay);
//        System.out.println(kh);
//        System.out.println(ma);
//        System.out.println(Home_GUI.txtSDTNV.getText());
//        HoaDon_model hoaDon = new HoaDon_model(ma, kh, nv, ngay + "", 0, 0, 0, 0, 0);
//        hoaDon_service.addHoaDon(hoaDon);
//        ShowTableHoaDon();
//        JOptionPane.showMessageDialog(this, "Oke");
    }

    private void ShowTableHoaDon() {
        listHoaDon = (ArrayList<HoaDon_model>) hoaDon_service.selectHoaDon();
        model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        for (HoaDon_model hd : listHoaDon) {
            String tt;
            if (hd.getTrangThai() == 0) {
                tt = "Chưa thanh toán";
            } else if (hd.getTrangThai() == 1) {
                tt = "Đã thanh toán";
            } else {
                tt = "Đã hủy";
            }
            model.addRow(new Object[]{hd.getMaHD(), hd.getKhachHang().getHoTen() + "__" + hd.getKhachHang().getSDT(), hd.getNhanVien().getHoTen() + "_" + hd.getNhanVien().getSDT(), hd.getNgayTao(), hd.getTongTien(), tt});
        }
    }

    private void ShowFormHoaDon(HoaDon_model hd) {
        txtMaHD.setText(hd.getMaHD());
        txtSDT.setText(hd.getKhachHang().getSDT());
        txtTen.setText(hd.getKhachHang().getHoTen());
        txtTienTichLuy.setText(hd.getKhachHang().getTienTichLuy() + "");
        txtChietKhau.setText(hd.getTienChietKhau() + "");
        txtPhaiTra.setText(hd.getTienThanhToan() + "");
        txtTienThuong.setText(hd.getTienThuong() + "");
        txtTienHang.setText(hd.getTongTien() + "");
        showTableHoaDonCT(hd.getMaHD());

    }

    private void ThemHoaDonCT(int index) {
        boolean check = false;
        SanPham_model sanPham = sanPhamService.selectByID(listSanPham.get(index).getId());
        if (sanPham.getSoLuong() == 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm đã hết");
            return;
        }
        String soLuongNhap = JOptionPane.showInputDialog(this, "Nhập vào số lượng");
        int soLuong = Integer.parseInt(soLuongNhap);
        if (sanPham.getSoLuong() < soLuong) {
            JOptionPane.showMessageDialog(this, "Sản phẩm không đủ số lượng");
            return;
        }
        for (HoaDonChiTiet_model hd : listHoaDonCT) {
            if (sanPham.getId() == hd.getSanPham().getId()) {
                System.out.println("oke");
                int sl = hd.getSoLuong() + soLuong;
                System.out.println(sl);
                HoaDonChiTiet_model hdct1 = new HoaDonChiTiet_model(hd.getId(), sl, (sl * (hd.getSanPham().getGiaBan())));
                hoaDonCT_service.UpdateHDCT(hdct1);
                check = true;
                break;
            }
        }
        if (check == false) {
            HoaDon_model hoaDon = hoaDon_service.selectHoaDonByID(txtMaHD.getText());
            HoaDonChiTiet_model hdct = new HoaDonChiTiet_model(0, hoaDon, sanPham, soLuong, (soLuong * (sanPham.getGiaBan())));
            hoaDonCT_service.AddHoaDonCT(hdct);
        }
        txtTienHang.setText(TienHang() + "");
        HoaDon_model hd = new HoaDon_model(txtMaHD.getText(), null, null, null, Float.parseFloat(txtTienHang.getText()), Float.parseFloat(txtChietKhau.getText()), Float.parseFloat(txtTienThuong.getText()), Float.parseFloat(txtPhaiTra.getText()), 0);
        hoaDon_service.updatetHD(hd);
        SanPham_model sp = new SanPham_model(sanPham.getId(), (sanPham.getSoLuong() - soLuong));
        sanPhamService.updateSL(sp);
        ShowTableSanPham();
        showTableHoaDonCT(txtMaHD.getText());
        ShowTableHoaDon();
        JOptionPane.showMessageDialog(this, "OKE");

    }

    private void ShowTableSanPham() {
        listSanPham = sanPhamService.selectSP();
        model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        cboDanhMucSearch.removeAllItems();
        cboLoaiSearch.removeAllItems();
        cboSizeSearch.removeAllItems();
        cboMauSearch.removeAllItems();
        for (SanPham_model sp : listSanPham) {
            cboDanhMucSearch.addItem(sp.getDanhMuc().getTenDanhMuc());
            cboLoaiSearch.addItem(sp.getLoai().getTenLoai());
            cboSizeSearch.addItem(sp.getSize().getSoSize());
            cboMauSearch.addItem(sp.getMau().getTenMau());
            model.addRow(new Object[]{sp.getId(), sp.getTenSanPham(), sp.getSize().getSoSize(), sp.getMau().getTenMau(), sp.getSoLuong(), sp.getGiaBan()});
        }

    }

    private void ShowTableSanPhamByTen(String tenSP) {
        listSanPham = sanPhamService.searchSanPham(tenSP);
        model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        for (SanPham_model sp : listSanPham) {
            model.addRow(new Object[]{sp.getId(), sp.getTenSanPham(), sp.getSize().getSoSize(), sp.getMau().getTenMau(), sp.getSoLuong(), sp.getGiaBan()});
        }

    }

    private void ShowTableSanPhamByChiTiet(String danhMucs) {
        listSanPham = sanPhamService.searchSanPhamByChiTiet(danhMucs);
        model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        for (SanPham_model sp : listSanPham) {
            model.addRow(new Object[]{sp.getId(), sp.getTenSanPham(), sp.getSize().getSoSize(), sp.getMau().getTenMau(), sp.getSoLuong(), sp.getGiaBan()});
        }

    }

    private float TienHang() {
        float tongTien = 0;
        index = tblHoaDon.getSelectedRow();
        for (HoaDonChiTiet_model hdct : hoaDonCT_service.selectHoaDon(txtMaHD.getText())) {
            tongTien += hdct.getTienHang();
            txtTienThuong.setText(String.valueOf((tongTien) * (20) / (100)));
        }
        return tongTien;

    }

    private void showTableHoaDonCT(String maHD) {
        listHoaDonCT = hoaDonCT_service.selectHoaDon(maHD);
        model = (DefaultTableModel) tblGioiHang.getModel();
        model.setRowCount(0);
        int stt = 0;
        for (HoaDonChiTiet_model hoaDonChiTiet_model : listHoaDonCT) {
            model.addRow(new Object[]{stt, hoaDonChiTiet_model.getSanPham().getTenSanPham(), hoaDonChiTiet_model.getSoLuong(), hoaDonChiTiet_model.getTienHang()});
            stt++;
        }
    }

    private void DeleteSanPhamHDCT() {
        SanPham_model sanPham = sanPhamService.selectByID(listSanPham.get(index).getId());
        HoaDonChiTiet_model hoaDonChiTiet = hoaDonCT_service.selectID(listHoaDonCT.get(index).getId());
        String soLuongNhap = JOptionPane.showInputDialog(this, "Nhập vào số lượng");
        int soLuong = Integer.parseInt(soLuongNhap);
        if (hoaDonChiTiet.getSoLuong() < soLuong) {
            JOptionPane.showMessageDialog(this, "Sản phẩm không đủ số lượng");
            return;
        }
        HoaDonChiTiet_model hdct = new HoaDonChiTiet_model(hoaDonChiTiet.getId(), (hoaDonChiTiet.getSoLuong() - soLuong), (hoaDonChiTiet.getSoLuong() - soLuong) * hoaDonChiTiet.getSanPham().getGiaBan());
        hoaDonCT_service.UpdateHDCT(hdct);
        if (hdct.getSoLuong() == 0) {
            hoaDonCT_service.DeleteHDCT(hdct.getId());
        }
        txtTienHang.setText(TienHang() + "");
        HoaDon_model hd = new HoaDon_model(txtMaHD.getText(), null, null, null, Float.parseFloat(txtTienHang.getText()), Float.parseFloat(txtChietKhau.getText()), Float.parseFloat(txtTienThuong.getText()), Float.parseFloat(txtPhaiTra.getText()), 0);
        hoaDon_service.updatetHD(hd);
//        System.out.println((hoaDonChiTiet.getSanPham().getSoLuong() + soLuong));
        SanPham_model sp = new SanPham_model(hoaDonChiTiet.getSanPham().getId(), (hoaDonChiTiet.getSanPham().getSoLuong() + soLuong));
//        DeleteHDCT(hoaDonChiTiet.getId());
        sanPhamService.updateSL(sp);
        ShowTableSanPham();
        ShowTableHoaDon();
        showTableHoaDonCT(txtMaHD.getText());
    }

    private void updateTrangThaiHD(int trangThai) {
        HoaDon_model hoaDon = new HoaDon_model(txtMaHD.getText(), null, null, null, 0, 0, 0, 0, trangThai);
        hoaDon_service.updatetTrangThaiHD(hoaDon);
        ShowTableHoaDon();
    }

//    private void DeleteHDCT(int id) {
//        for (HoaDonChiTiet_model hoaDonChiTiet_model : listHoaDonCT) {
//            if (hoaDonChiTiet_model.getSoLuong() == 0) {
//                hoaDonCT_service.DeleteHDCT(id);
//            }
//        }
//    }
    private void inHoaDon() {
        Document document = new Document();
        SimpleDateFormat dateFM = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        String maHD = txtMaHD.getText();
        HoaDon_model hd = hoaDon_service.selectHoaDonByID(maHD);
        NhanVien_model nv = hd.getNhanVien();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\tuan0\\Downloads\\HoaDon\\" + txtMaHD.getText() + ".pdf"));
            document.open();
//            Tạo 4 colum
            PdfPTable table = new PdfPTable(4);
//            Tạo 4 cột
            PdfPCell stt = new PdfPCell(new Paragraph("STT"));
            PdfPCell sanPham = new PdfPCell(new Paragraph("SanPham"));
            PdfPCell soLuong = new PdfPCell(new Paragraph("SoLuong"));
            PdfPCell gia = new PdfPCell(new Paragraph("GiaTien"));
            stt.setBorder(0);
            sanPham.setBorder(0);
            gia.setBorder(0);
            soLuong.setBorder(0);
            float[] columnWidths = {0.5f, 1f, 1.5f, 0.5f};
            table.setWidths(columnWidths);
            table.addCell(stt);
            table.addCell(sanPham);
            table.addCell(soLuong);
            table.addCell(gia);

//            HDCT
            for (int i = 0; i < tblGioiHang.getRowCount(); i++) {

                PdfPCell hdSTT = new PdfPCell(new Paragraph(tblGioiHang.getValueAt(i, 0).toString()));
//                System.out.println(hdSanPham);
                PdfPCell hdTen = new PdfPCell(new Paragraph((tblGioiHang.getValueAt(i, 1).toString())));
                PdfPCell hdSoLuong = new PdfPCell(new Paragraph(tblGioiHang.getValueAt(i, 2).toString()));
                PdfPCell hdThanhTien = new PdfPCell(new Paragraph(tblGioiHang.getValueAt(i, 3).toString()));
                hdSTT.setBorder(0);
                hdTen.setBorder(0);
                hdSoLuong.setBorder(0);
                hdThanhTien.setBorder(0);
                float[] columnDB = {0.5f, 1f, 1.5f, 0.5f};
                table.setWidths(columnDB);
                table.addCell(hdSTT);
                table.addCell(hdTen);
                table.addCell(hdSoLuong);
                table.addCell(hdThanhTien);
            }
            Paragraph paragraph1 = new Paragraph("--------------------------------------------------------------\n");
            Paragraph paragraph2 = new Paragraph("TienHang:   " + txtTienHang.getText()
                    + "\nChietKhau:   " + txtChietKhau.getText()
                    + "\nTienThuong:  " + txtTienThuong.getText()
                    + "\nTongTien:    " + txtPhaiTra.getText());
            paragraph1.setIndentationLeft(80);
            paragraph1.setIndentationRight(80);
            paragraph1.setAlignment(Element.ALIGN_CENTER);
            paragraph1.setSpacingAfter(15);
            paragraph2.setIndentationLeft(340);
            paragraph2.setSpacingBefore(15);
            paragraph2.setAlignment(Element.ALIGN_LEFT);
            document.add(table);
            document.add(paragraph1);
            document.add(paragraph2);
            document.close();
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
