/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.NhanVien_model;
import Service.NhanVien_service;
import Service_impl.NhanVien_impl;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tuan0
 */
public class DangNhap_GUI extends javax.swing.JFrame {

    NhanVien_impl nhanVien = new NhanVien_service();
    int index;
    String srtAnh = "";
//    Home_GUI home = new Home_GUI();

    /**
     * Creates new form DangNhap_GUI
     */
    public DangNhap_GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        checkPass = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 130, 180));
        jLabel2.setText("SĐT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 130, 180)));
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 130, 180));
        jLabel3.setText("Mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        txtMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 130, 180)));
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 40));

        checkPass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        checkPass.setForeground(new java.awt.Color(70, 130, 180));
        checkPass.setText("Hiện thị mật khẩu");
        getContentPane().add(checkPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(70, 130, 180));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thoát");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, 40));

        btnDangNhap.setBackground(new java.awt.Color(70, 130, 180));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/360_F_403029269_KCrGHt5AdtV7GSD2KeP8Wk2PYIbVKlNU.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if (checkForm() == false) {
            return;
        }
        NhanVien_model nv = getNhanVien();
        if (nv != null) {
                Home_GUI home = new Home_GUI();
            home.txtAnh.setText(nv.getHoTen());
            String tt = "";
            if (nv.getVaiTro() == 0) {
                tt = "Quản lý";
            } else {
                tt = "Nhân viên";
            }
//            Home_GUI.txtTen.setText(nv.getHoTen() + "__" + tt);
            home.txtSDTNV.setText(nv.getSDT());
//            Home_GUI.lblBanHang.setText(nv.getSDT());
//            setImages(nv.getAnh());
            srtAnh = nv.getAnh();
            home.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
        }


    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
    private NhanVien_model getNhanVien() {
        String sdt = txtSDT.getText();
        String matKhau = txtMatKhau.getText();
        NhanVien_model nv = nhanVien.loginNV(sdt, matKhau);
        return nv;
    }

    private boolean checkForm() {
        if (txtSDT.getText().length() == 0 && txtMatKhau.getText().length() == 0) {
            return false;
        } else {
            return true;
        }
    }

//    public void setImages(String image) {
//        if (image == null) {
//            image = "src/icon/logo_blue.png";
//        }
//        ImageIcon images = new ImageIcon(image);
//        Image im = images.getImage();
//        ImageIcon icon = new ImageIcon(im.getScaledInstance(home.txtAnh.getWidth(), home.txtAnh.getHeight(), im.SCALE_SMOOTH));
//        home.txtAnh.setText(null);
//        home.txtAnh.setIcon(icon);
//    }

//    public void setImages(String image) {
//        if (image == null) {
//            image = "src/icon/logo_blue.png";
//        }
//        ImageIcon images = new ImageIcon(image);
//        Image im = images.getImage();
//        ImageIcon icon = new ImageIcon(im.getScaledInstance(home.txtTenNV.getWidth(), home.txtTenNV.getHeight(), im.SCALE_SMOOTH));
//        home.txtTenNV.setText(null);
//        home.txtTenNV.setIcon(icon);
//    }
}
