/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.DanhMuc_model;
import Model.Loai_model;
import Model.MauSac_model;
import Model.SanPham_model;
import Model.Size_model;
import Service.DanhMuc_Service;
import Service.Loai_Service;
import Service.MauSac_Service;
import Service.SanPham_Service;
import Service.Size_Service;
import Service_impl.DanhMuc_impl;
import Service_impl.Loai_impl;
import Service_impl.MauSac_impl;
import Service_impl.SanPham_impl;
import Service_impl.Size_impl;
import java.awt.Image;
import java.io.File;
import java.text.Collator;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuan0
 */
public class SanPham_GUI extends javax.swing.JPanel {

    List<DanhMuc_model> listDanhMuc = new ArrayList<>();
    List<Loai_model> listLoai = new ArrayList<>();
    List<MauSac_model> listMau = new ArrayList<>();
    List<Size_model> listSize = new ArrayList<>();
    List<SanPham_model> listSanPham = new ArrayList<>();
    DanhMuc_impl danhMucService = new DanhMuc_Service();
    Loai_impl loaiService = new Loai_Service();
    MauSac_impl mauService = new MauSac_Service();
    Size_impl sizeService = new Size_Service();
    SanPham_impl sanPhamService = new SanPham_Service();
    DefaultTableModel model = new DefaultTableModel();
    int index;
    String srtAnh = "";

    /**
     * Creates new form SanPham_GUI
     */
    public SanPham_GUI() {
        initComponents();
        txtID.setEnabled(false);
        showTableDanhMuc();
        showTableLoai();
        showTableMau();
        showTableSize();
        showTableSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        btnThemDanhMuc = new javax.swing.JButton();
        btnThemLoai = new javax.swing.JButton();
        btnThemSize = new javax.swing.JButton();
        btnThemMau = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtHinhAnh = new javax.swing.JLabel();
        rdoConHang = new javax.swing.JRadioButton();
        rdoHetHang = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        min = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        cboDanhMuc_Search = new javax.swing.JComboBox<>();
        cboLoai_Search = new javax.swing.JComboBox<>();
        cboMau_Search = new javax.swing.JComboBox<>();
        cboSize_Search = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTenChiTiet = new javax.swing.JTextField();
        rdoDanhMuc = new javax.swing.JRadioButton();
        rdoLoai = new javax.swing.JRadioButton();
        rdoSize = new javax.swing.JRadioButton();
        rdoMau = new javax.swing.JRadioButton();
        btnAddChiTiet = new javax.swing.JButton();
        btnUpdateCT = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();

        jTextField4.setText("jTextField1");

        jLabel4.setText("Giá nhập");

        setPreferredSize(new java.awt.Dimension(1182, 774));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1182, 774));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1178, 744));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tên sản phẩm");

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Giá nhập");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giá bán");

        cboDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Danh mục");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Loại");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Size");

        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Màu");

        cboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemDanhMuc.setBackground(new java.awt.Color(70, 130, 180));
        btnThemDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDanhMuc.setText("+");
        btnThemDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDanhMucActionPerformed(evt);
            }
        });

        btnThemLoai.setBackground(new java.awt.Color(70, 130, 180));
        btnThemLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLoai.setText("+");
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        btnThemSize.setBackground(new java.awt.Color(70, 130, 180));
        btnThemSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSize.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSize.setText("+");
        btnThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSizeActionPerformed(evt);
            }
        });

        btnThemMau.setBackground(new java.awt.Color(70, 130, 180));
        btnThemMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMau.setText("+");
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHinhAnh.setText("Ảnh");
        txtHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHinhAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        buttonGroup2.add(rdoConHang);
        rdoConHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoConHang.setText("Còn hàng");

        buttonGroup2.add(rdoHetHang);
        rdoHetHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoHetHang.setText("Hết hàng");

        jButton1.setBackground(new java.awt.Color(70, 130, 180));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(70, 130, 180));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(70, 130, 180));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(70, 130, 180));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        min.setText("Sản phẩm:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboSize, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemMau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdoConHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoHetHang)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(min)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboDanhMuc, txtTenSP});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cboDanhMuc)
                                        .addComponent(btnThemDanhMuc)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(btnThemLoai))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnThemSize))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnThemMau)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoConHang)
                            .addComponent(rdoHetHang)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(min)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThemDanhMuc, btnThemLoai, btnThemMau, btnThemSize, cboDanhMuc, jButton1, jButton2, jButton3, jButton4, txtTenSP});

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số lượng", "Giá bán", "Giá nhận", "Danh mục", "Loại", "Size", "Màu", "HinhAnh"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cboDanhMuc_Search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboLoai_Search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoai_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoai_SearchActionPerformed(evt);
            }
        });

        cboMau_Search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMau_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMau_SearchActionPerformed(evt);
            }
        });

        cboSize_Search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSize_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSize_SearchActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Tên sản phẩm");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Danh mục");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Loại");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Màu");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Size");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDanhMuc_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoai_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboMau_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(cboSize_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboDanhMuc_Search, cboLoai_Search, cboMau_Search, cboSize_Search});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDanhMuc_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoai_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMau_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSize_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboDanhMuc_Search, cboLoai_Search, cboMau_Search, cboSize_Search});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Mã ");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Tên");

        buttonGroup1.add(rdoDanhMuc);
        rdoDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoDanhMuc.setText("Danh mục");
        rdoDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDanhMucActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoLoai);
        rdoLoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoLoai.setText("Loại");
        rdoLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoLoaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoSize);
        rdoSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoSize.setText("Size");
        rdoSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSizeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMau);
        rdoMau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMau.setText("Màu");
        rdoMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMauActionPerformed(evt);
            }
        });

        btnAddChiTiet.setBackground(new java.awt.Color(70, 130, 180));
        btnAddChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnAddChiTiet.setText("ADD");
        btnAddChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChiTietActionPerformed(evt);
            }
        });

        btnUpdateCT.setBackground(new java.awt.Color(70, 130, 180));
        btnUpdateCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateCT.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCT.setText("UPDATE");
        btnUpdateCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCTActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(70, 130, 180));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(70, 130, 180));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(rdoDanhMuc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdoMau, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(txtTenChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rdoLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(rdoSize, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnAddChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateCT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtTenChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoDanhMuc)
                    .addComponent(rdoLoai)
                    .addComponent(rdoSize)
                    .addComponent(rdoMau))
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên"
            }
        ));
        tblChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblChiTiet);

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi tiết", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void cboLoai_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoai_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoai_SearchActionPerformed

    private void cboMau_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMau_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMau_SearchActionPerformed

    private void cboSize_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSize_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSize_SearchActionPerformed

    private void rdoDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDanhMucActionPerformed
        // TODO add your handling code here:
        if (rdoDanhMuc.isSelected() == true) {
            showTableDanhMuc();
        } else {
            clearFormChiTiet();
        }
    }//GEN-LAST:event_rdoDanhMucActionPerformed

    private void rdoSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSizeActionPerformed
        // TODO add your handling code here:
        if (rdoSize.isSelected() == true) {
            showTableSize();
        } else {
            clearFormChiTiet();
        }
    }//GEN-LAST:event_rdoSizeActionPerformed

    private void rdoLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoLoaiActionPerformed
        // TODO add your handling code here:
        if (rdoLoai.isSelected() == true) {
            showTableLoai();
        } else {
            clearFormChiTiet();
        }
    }//GEN-LAST:event_rdoLoaiActionPerformed

    private void rdoMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMauActionPerformed
        // TODO add your handling code here:
        if (rdoMau.isSelected() == true) {
            showTableMau();
        } else {
            clearFormChiTiet();
        }
    }//GEN-LAST:event_rdoMauActionPerformed

    private void tblChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietMouseClicked
        // TODO add your handling code here:
        index = tblChiTiet.getSelectedRow();
        showFormChiTiet();
    }//GEN-LAST:event_tblChiTietMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFormChiTiet();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChiTietActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận thêm: " + txtTenChiTiet.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            addChiTiet();
        } else {
            JOptionPane.showConfirmDialog(this, "Tao tác bị hủy");
        }
    }//GEN-LAST:event_btnAddChiTietActionPerformed

    private void btnUpdateCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCTActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận Cập nhật: " + txtTenChiTiet.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            updateChiTiet();
        } else {
            JOptionPane.showMessageDialog(this, "Tao tác bị hủy");
        }
    }//GEN-LAST:event_btnUpdateCTActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận xóa: " + txtTenChiTiet.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            deleteChiTiet();
        } else {
            JOptionPane.showMessageDialog(this, "Tao tác bị hủy");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        if (rdoDanhMuc.isSelected() == true) {
            searchDanhMuc(txtTimKiem.getText());
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnThemDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDanhMucActionPerformed
        // TODO add your handling code here:
        String tenDM = JOptionPane.showInputDialog("Nhập tên danh mục");
        DanhMuc_model danhMuc = new DanhMuc_model(0, tenDM);
        danhMucService.addDM(danhMuc);
        showTableDanhMuc();
        JOptionPane.showMessageDialog(this, "Thêm thành công");


    }//GEN-LAST:event_btnThemDanhMucActionPerformed

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        // TODO add your handling code here:
        String tenLoai = JOptionPane.showInputDialog("Nhập tên loại");
        Loai_model loai = new Loai_model(0, tenLoai);
        loaiService.addLoai(loai);
        showTableLoai();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void btnThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSizeActionPerformed
        // TODO add your handling code here:
        String tenSize = JOptionPane.showInputDialog("Nhập tên size");
        Size_model size = new Size_model(0, tenSize);
        sizeService.addSize(size);
        showTableSize();
        JOptionPane.showMessageDialog(this, "Thêm thành công");

    }//GEN-LAST:event_btnThemSizeActionPerformed

    private void btnThemMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauActionPerformed
        // TODO add your handling code here:
        String tenMau = JOptionPane.showInputDialog("Nhập tên màu");
        MauSac_model mau = new MauSac_model(0, tenMau);
        mauService.addMau(mau);
        showTableMau();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btnThemMauActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UpdateSanPham();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        index = tblSanPham.getSelectedRow();
        showFormSanPham();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHinhAnhMouseClicked
        // TODO add your handling code here:
        fileAnh();
    }//GEN-LAST:event_txtHinhAnhMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AddSanPham();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ClearForm();
        kiemTranGiaMin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DeleteSanPham();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddChiTiet;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnThemDanhMuc;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnThemSize;
    private javax.swing.JButton btnUpdateCT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboDanhMuc_Search;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboLoai_Search;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboMau_Search;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboSize_Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel min;
    private javax.swing.JRadioButton rdoConHang;
    private javax.swing.JRadioButton rdoDanhMuc;
    private javax.swing.JRadioButton rdoHetHang;
    private javax.swing.JRadioButton rdoLoai;
    private javax.swing.JRadioButton rdoMau;
    private javax.swing.JRadioButton rdoSize;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JLabel txtHinhAnh;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenChiTiet;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void showTableDanhMuc() {
        listDanhMuc = (ArrayList<DanhMuc_model>) danhMucService.selectDM();
        model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        cboDanhMuc.removeAllItems();
        cboDanhMuc_Search.removeAllItems();
        for (DanhMuc_model danhMuc_model : listDanhMuc) {
            cboDanhMuc_Search.addItem(danhMuc_model.getTenDanhMuc());
            cboDanhMuc.addItem(danhMuc_model.getTenDanhMuc());
            model.addRow(new Object[]{danhMuc_model.getMaDanhMuc(), danhMuc_model.getTenDanhMuc()});
        }
    }

    private void searchDanhMuc(String keyWord) {
        listDanhMuc = (ArrayList<DanhMuc_model>) danhMucService.search(keyWord);
        model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        for (DanhMuc_model danhMuc_model : listDanhMuc) {
            model.addRow(new Object[]{danhMuc_model.getMaDanhMuc(), danhMuc_model.getTenDanhMuc()});
        }
    }

    private void showTableLoai() {
        listLoai = (ArrayList<Loai_model>) loaiService.selectLoai();
        model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        cboLoai.removeAllItems();
        cboLoai_Search.removeAllItems();
        for (Loai_model loai : listLoai) {
            model.addRow(new Object[]{loai.getId(), loai.getTenLoai()});
            cboLoai.addItem(loai.getTenLoai());
            cboLoai_Search.addItem(loai.getTenLoai());
        }
    }

    private void showTableMau() {
        listMau = (ArrayList<MauSac_model>) mauService.selectMau();
        model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        cboMau.removeAllItems();
        cboMau_Search.removeAllItems();
        for (MauSac_model mauSac_model : listMau) {
            model.addRow(new Object[]{mauSac_model.getId(), mauSac_model.getTenMau()});
            cboMau.addItem(mauSac_model.getTenMau());
            cboMau_Search.addItem(mauSac_model.getTenMau());
        }
    }

    private void showTableSize() {
        listSize = (ArrayList<Size_model>) sizeService.selectSize();
        model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        cboSize.removeAllItems();
        cboSize_Search.removeAllItems();
        for (Size_model size_model : listSize) {
            model.addRow(new Object[]{size_model.getId(), size_model.getSoSize()});
            cboSize.addItem(size_model.getSoSize());
            cboSize_Search.addItem(size_model.getSoSize());
        }
    }

    private void showFormChiTiet() {
        txtID.setText(tblChiTiet.getValueAt(index, 0) + "");
        txtTenChiTiet.setText(tblChiTiet.getValueAt(index, 1) + "");
    }

    private void clearFormChiTiet() {
        String clear = "";
        txtID.setText(clear);
        txtTenChiTiet.setText(clear);
    }

    private void addChiTiet() {
        try {
//            Add danh muc
            if (rdoDanhMuc.isSelected() == true) {
                DanhMuc_model danhMuc = new DanhMuc_model(0, txtTenChiTiet.getText());
                danhMucService.addDM(danhMuc);
                showTableDanhMuc();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
//            Add loai
            if (rdoLoai.isSelected() == true) {
                Loai_model loai = new Loai_model(0, txtTenChiTiet.getText());
                loaiService.addLoai(loai);
                showTableLoai();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
//            Add Mau
            if (rdoMau.isSelected() == true) {
                MauSac_model mau = new MauSac_model(0, txtTenChiTiet.getText());
                mauService.addMau(mau);
                showTableMau();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
//            Add Size
            if (rdoSize.isSelected() == true) {
                Size_model size = new Size_model(0, txtTenChiTiet.getText());
                sizeService.addSize(size);
                showTableSize();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro");
        }
    }

    private void updateChiTiet() {
        try {
//            update danh muc
            if (rdoDanhMuc.isSelected() == true) {
                DanhMuc_model danhMuc = new DanhMuc_model(Integer.parseInt(txtID.getText()), txtTenChiTiet.getText());
                danhMucService.updateDM(danhMuc);
                showTableDanhMuc();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
//            update loai
            if (rdoLoai.isSelected() == true) {
                Loai_model loai = new Loai_model(Integer.parseInt(txtID.getText()), txtTenChiTiet.getText());
                loaiService.updateLoai(loai);
                showTableLoai();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
//            update Mau
            if (rdoMau.isSelected() == true) {
                MauSac_model mau = new MauSac_model(Integer.parseInt(txtID.getText()), txtTenChiTiet.getText());
                mauService.updateMau(mau);
                showTableMau();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
//            update Size
            if (rdoSize.isSelected() == true) {
                Size_model size = new Size_model(Integer.parseInt(txtID.getText()), txtTenChiTiet.getText());
                sizeService.updateSize(size);
                showTableSize();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro");
        }
    }

    private void deleteChiTiet() {
        try {
//            delete danh muc
            if (rdoDanhMuc.isSelected() == true) {
                danhMucService.deleteDM(txtID.getText());
                showTableDanhMuc();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
//            delete loai
            if (rdoLoai.isSelected() == true) {
                loaiService.deleteLoai(txtID.getText());
                showTableLoai();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
//            delete Mau
            if (rdoMau.isSelected() == true) {
                mauService.deleteDM(txtID.getText());
                showTableMau();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
//            delete Size
            if (rdoSize.isSelected() == true) {
                sizeService.deleteSize(txtID.getText());
                showTableSize();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro");
        }
    }

    private void showTableSanPham() {
        listSanPham = (ArrayList<SanPham_model>) sanPhamService.selectSP();
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        for (SanPham_model sp : listSanPham) {
            model.addRow(new Object[]{sp.getId(), sp.getTenSanPham(), sp.getSoLuong(), sp.getGiaBan(), sp.getGiaNhap(), sp.getDanhMuc().getTenDanhMuc(), sp.getLoai().getTenLoai(), sp.getSize().getSoSize(), sp.getMau().getTenMau(), sp.getAnh()});
        }
    }

    private void AddSanPham() {
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận thêm sản phẩm: " + txtTenSP.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            String tenSanPham = txtTenSP.getText();
            int tt;
            if (listSanPham.get(index).getSoLuong() == 0) {
                tt = 0;
            } else {
                tt = 1;
            }
            int danhmuc = listDanhMuc.get(cboDanhMuc.getSelectedIndex()).getMaDanhMuc();
            System.out.println(danhmuc);
            int loai = listLoai.get(cboLoai.getSelectedIndex()).getId();
            System.out.println(loai);
            int mau = listMau.get(cboMau.getSelectedIndex()).getId();
            System.out.println(mau);
            int size = listSize.get(cboSize.getSelectedIndex()).getId();
            System.out.println(size);
            DanhMuc_model dm = danhMucService.selectByID(danhmuc);
            Loai_model l = loaiService.selectByID(loai);
            MauSac_model m = mauService.selectByID(mau);
            Size_model s = sizeService.selectByID(size);
            int id = (int) tblSanPham.getValueAt(index, 0);
            String anh = srtAnh;
            SanPham_model sp = new SanPham_model(0, tenSanPham, dm, l, m, s, Float.parseFloat(txtGiaNhap.getText()), Float.parseFloat(txtGiaBan.getText()), Integer.parseInt(txtSoLuong.getText()), anh, tt);
            sanPhamService.addSanPham(sp);
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            showTableSanPham();
            ClearForm();
        }
    }

    private void UpdateSanPham() {
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận sửa sản phẩm: " + txtTenSP.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            String tenSanPham = txtTenSP.getText();
            int tt;
            if (listSanPham.get(index).getSoLuong() == 0) {
                tt = 0;
            } else {
                tt = 1;
            }
            int danhmuc = listDanhMuc.get(cboDanhMuc.getSelectedIndex()).getMaDanhMuc();
            System.out.println(danhmuc);
            int loai = listLoai.get(cboLoai.getSelectedIndex()).getId();
            System.out.println(loai);
            int mau = listMau.get(cboMau.getSelectedIndex()).getId();
            System.out.println(mau);
            int size = listSize.get(cboSize.getSelectedIndex()).getId();
            System.out.println(size);
            DanhMuc_model dm = danhMucService.selectByID(danhmuc);
            Loai_model l = loaiService.selectByID(loai);
            MauSac_model m = mauService.selectByID(mau);
            Size_model s = sizeService.selectByID(size);
            int id = (int) tblSanPham.getValueAt(index, 0);
            String anh = srtAnh;
            SanPham_model sp = new SanPham_model((int) tblSanPham.getValueAt(index, 0), tenSanPham, dm, l, m, s, Float.parseFloat(txtGiaNhap.getText()), Float.parseFloat(txtGiaBan.getText()), Integer.parseInt(txtSoLuong.getText()), anh, tt);
            sanPhamService.updateDM(sp);
            showTableSanPham();
            ClearForm();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật không thành công");
        }
    }

    private void DeleteSanPham() {
        int xacNhan = JOptionPane.showConfirmDialog(this, "Xác nhận xóa sản phẩm: " + txtTenSP.getText());
        if (xacNhan == JOptionPane.YES_OPTION) {
            int id = (int) tblSanPham.getValueAt(index, 0);
            sanPhamService.deleteDM(id + "");
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            showTableSanPham();
            ClearForm();
        }
    }

    private void ClearForm() {
        String xoaTrang = "";
        txtTenSP.setText(xoaTrang);
        txtGiaNhap.setText(xoaTrang);
        txtGiaBan.setText(xoaTrang);
        txtSoLuong.setText(xoaTrang);
        txtHinhAnh.setText("Chọn ảnh");
        cboDanhMuc.setSelectedIndex(0);
        cboSize.setSelectedIndex(0);
        cboLoai.setSelectedIndex(0);
        cboMau.setSelectedIndex(0);

    }

    private void showFormSanPham() {
        if (listSanPham.get(index).getTrangThai() == 0) {
            rdoConHang.setSelected(true);
        } else {
            rdoHetHang.setSelected(true);
        }
        txtTenSP.setText((String) tblSanPham.getValueAt(index, 1));
        txtSoLuong.setText(tblSanPham.getValueAt(index, 2) + "");
        txtGiaNhap.setText(tblSanPham.getValueAt(index, 3) + "");
        txtGiaBan.setText(tblSanPham.getValueAt(index, 4) + "");
        cboDanhMuc.setSelectedItem(listSanPham.get(index).getDanhMuc().getTenDanhMuc());
        cboLoai.setSelectedItem(listSanPham.get(index).getLoai().getTenLoai());
        cboMau.setSelectedItem(listSanPham.get(index).getMau().getTenMau());
        cboSize.setSelectedItem(listSanPham.get(index).getSize().getSoSize());
        setImages(listSanPham.get(index).getAnh());
        srtAnh = listSanPham.get(index).getAnh();
    }

    private void fileAnh() {
        JFileChooser filechooser = new JFileChooser("C:\\\\Users\\\\tuan0\\\\OneDrive\\\\Máy tính\\\\Java_core\\\\DUAN_BANHANG\\\\src\\\\image");
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh anh", "jpg", "jpeg", "png", "webp");
        filechooser.setFileFilter(imageFilter);
        int x = filechooser.showDialog(this, "Chọn Hình Ảnh");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = filechooser.getSelectedFile();
            srtAnh = f.getAbsolutePath();
            txtHinhAnh.removeAll();
            setImages(srtAnh);
        }
    }

    public void setImages(String image) {
        if (image == null) {
            image = "src/icon/logo_blue.png";
        }
        ImageIcon images = new ImageIcon(image);
        Image im = images.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(txtHinhAnh.getWidth(), txtHinhAnh.getHeight(), im.SCALE_SMOOTH));
        txtHinhAnh.setText(null);
        txtHinhAnh.setIcon(icon);
    }

    private void kiemTranGiaMin() {
        
    }

}
